### ISSUE TITLE
Do synchronous networking in Android or restructure

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#2]
The Java code in `Connection.java` is totally broken at the moment. There's a conceptual problem: I want my networking/IO to be blocking, not asynchronous, because I can't do anything useful while waiting. OTOH, I want the event loop to continue.

**Comment by okitec** [comment]
Perhaps I could use `go bind` and reduce the amount of Java to the GUI glue where it belongs :stuck_out_tongue:

**Comment by okitec** [comment]
Asynchronous networking should be possible, but the answers by the server don't carry info about the request; it is a stateful protocol.

**Comment by okitec** [comment]
**Proposal**
Reintroduce message tags: the client shall again provide a message tag which the server will prepend to its answer. On the app side, we could have a table mapping outstanding requests to the handler method that knows what to do with the content.

To know how something went, we need error and success indicators now, overriding the  Unix *Rule of Silence* a bit.

**Comment by okitec** [comment]
This issue is kind of solved now, but it hasn't been **tested**.

**Comment by leletec** [comment]
Dat tag though.

**Comment by okitec** [comment]
It is the bane of my existance up to this point. I've been half-heartedly "solving" it for half a year now. *ugh*

**Comment by leletec** [comment]
I believe in you.

**Comment by okitec** [comment]
I shall sidestep this issue and override the `NetworkingInMainThread` safeguard. I don't care! In Plan 9, everything is blocking and still single-threaded UIs still feel responsive.

**Comment by leletec** [comment]
That might be the best for now.
"I don't care" is sometimes a good strat.

**Comment by okitec** [comment]
Closed by d186b6aa9f438e7cc8db46b8daa5a1b41c76ddfc
