### ISSUE TITLE
Lend a set of copies to user

### ISSUE THREAD

**Issue by okitec** [okitec/libmangler#48]
There is a mismatch between my model and the reality of a school book system: when lending, you commonly prepare a stack of copies where each copy is a different book, then lend them to the user.

- [x] The really easy part: In the app, there should be a button on the **User** screen to lend a copy that will be scanned. That way, the user's name needs not be retyped all the time. Care must be taken in `getActivityResult` to switch back to the user info screen instead of the copy screen **and** not reset the ID at the start of `userinfo`.

**Points to ponder**

 - QR code scanning is sequential and slow. Using RFID/NFC tags embedded in every book would work for NFC-enabled phones and is probably faster (Is that so, @leletec?). Downside: cost. The Stadtbücherei uses them, however.
 - Storing the physical positions of copies (row, column, stack; probably less, because copies of a book are stacked) can, like any metadata, be achieved with tags or by filing a note and metadata-searching it. This would also solve the problem, but is prone to user error.
 - Preparing a set of books is easy: just assign them a tag, e.g. #Q11.
 - Getting a set of unassigned copies for a set of books is not directly possible in the protocol.
 - If the IDs of that set were quasi-randomly selected, they bear no relation to physical storage unless the position is stored with them. Rummaging through heaps of copies to find one with a certain ID is probably more time-consuming than simply scanning any copy and lending it.

**Comment by leletec** [comment]
Yes, NFC should really be faster then reading a QR code.
 - QR code can be quick, but can also be really slow (cf. web.whatsapp.com)
 - Sending data via NFC is realtively fast (sending my database file takes around 5 seconds; another example: Amiibo)

 -> Reading an NFC-Tag should be really quick

**Comment by okitec** [comment]
Imagine sitting there, slowly reading the QR code of **every** **single** of these copies in a stack instead of just having the pupil plot down their signature. :unamused:
